parameters:
    phpbb.postas.postas_table: '%core.table_prefix%phpbb_postas'

services:
    phpbb.postas.listener:
        class: phpbb\postas\event\listener
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@template'
            - '@request'
            - '%core.table_prefix%'
            - '@config'
        tags:
            - { name: event.listener }
    phpbb.postas.controller.acp:
        class: phpbb\postas\controller\acp_controller
        arguments:
            - '@config'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
