services:
    booskit.darkmode.listener:
        class: booskit\darkmode\event\listener
        arguments:
            - '@template'
            - '@user'
            - '@request'
            - '@config'
        tags:
            - { name: event.listener }
